version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: secret
    volumes:
      - ~/survey_api/db:/var/lib/postgresql/data
  web:
    build: .
    ports:
      - 80:80
    environment:
      DATABASE_URL: postgresql://postgres:secret@db:5432
      SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      ACCESS_TOKEN_EXPIRE_MINUTES: 10080
    depends_on:
      - db